# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - gosimple       # Simplify code
    - govet          # Vet examines Go source code
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Static analysis
    - unused         # Check for unused code
    - gofmt          # Check code formatting
    - goimports      # Check import formatting
    - misspell       # Find commonly misspelled words
    - gocritic       # Comprehensive Go linter
    - revive         # Fast, configurable linter
    - gosec          # Security issues
    - bodyclose      # Check HTTP response body closed
    - noctx          # Find sending HTTP request without context.Context
    - sqlclosecheck  # Check SQL rows/statements closed
    - rowserrcheck   # Check Rows.Err is checked
    - stylecheck     # Style checks
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Find unused function parameters
    - whitespace     # Find unnecessary whitespace

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: false

  govet:
    check-shadowing: false

  gofmt:
    simplify: true

  goimports:
    local-prefixes: go-starter

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  gosec:
    excludes:
      - G404  # Use of weak random number generator - OK for non-crypto

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    # Exclude duplicate code check for migration files
    - path: internal/migrations/
      linters:
        - dupl

  max-same-issues: 0
  max-issues-per-linter: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
